//! This module contains the database schema definitions for the JWK microservice.
//! It is automatically generated by Diesel CLI.

diesel::table! {
    /// Table representing JWKs (JSON Web Keys).
    jwks (id) {
        /// Unique key identifier.
        id -> Uuid,
        /// Key type (e.g., "RSA").
        kty -> Varchar,
        /// Algorithm used with the key (e.g., "RS256").
        alg -> Varchar,
        /// Key ID.
        kid -> Varchar,
        /// Key modulus in Base64 format.
        n -> Text,
        /// Public exponent in Base64 format.
        e -> Text,
        /// Private key in Base64 format.
        d -> Text,
        /// Key creation date.
        created_at -> Timestamp,
        /// Key deletion date. If `NULL`, the key is active.
        deleted_at -> Nullable<Timestamp>,
        /// Private key expiration date.
        private_key_expires_at -> Nullable<Timestamp>,
        /// Key expiration date.
        key_expires_at -> Nullable<Timestamp>,
    }
}