name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Run Clippy
        run: cargo clippy -- -D warnings