name: Tests and Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: jwk_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          cargo install diesel_cli --no-default-features --features postgres
          cargo install cargo-tarpaulin

      - name: Set up PostgreSQL environment
        run: |
          echo "DATABASE_URL=postgres://user:password@localhost:5432/jwk_db" >> $GITHUB_ENV

      - name: Prepare system
        run: |
          diesel migration run

      - name: Run tests
        run: cargo test

      - name: Run coverage
        run: cargo tarpaulin --ignore-tests # --out Lcov